config/routes.rb
Rails.application.routes.draw do
  root 'splash#index'
  namespace :api do
    namespace :v1 do
      get 'resources', to: 'resources#index'
    end
  end

  resources :manifests
  resources :considerations
  resources :definitions
  resources :preambles
  resources :recitals
  resources :clauses
end

app/models/preamble.rb
class Preamble
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Versioning
  include Mongoid::Paranoia

  field :title, type: String
  field :body, type: String
  field :meta, type: Hash
end

app/controllers/preambles_controller.rb
class PreamblesController < ApplicationController
  before_action :set_preamble, only: [:show, :edit, :update, :destroy]

  # GET /preambles
  def index
    @preambles = Preamble.all
  end

  # GET /preambles/1
  def show
  end

  # GET /preambles/new
  def new
    @preamble = Preamble.new
  end

  # GET /preambles/1/edit
  def edit
  end

  # POST /preambles
  def create
    @preamble = Preamble.new(preamble_params)

    if @preamble.save
      respond_to do |format|
        format.html { redirect_to @preamble, notice: 'Preamble was successfully created.' }
        format.json { render json: { data: @preamble.as_json } }
      end
    else
      render :new
    end
  end

  # PATCH/PUT /preambles/1
  def update
    if @preamble.update(preamble_params)
      respond_to do |format|
        format.html { redirect_to @preamble, notice: 'Preamble was successfully updated.' }
        format.json { render json: { data: @preamble.as_json } }
      end
    else
      render :edit
    end
  end

  # DELETE /preambles/1
  def destroy
    @preamble.destroy
    redirect_to preambles_url, notice: 'Preamble was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preamble
      @preamble = Preamble.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def preamble_params
      params.require(:preamble).permit(:title, :body, :meta)
    end
end

app/helpers/preambles_helper.rb
module PreamblesHelper
end

app/views/preambles/_form.html.erb
<%= form_for(@preamble) do |f| %>
  <% if @preamble.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@preamble.errors.count, "error") %> prohibited this preamble from being saved:</h2>

      <ul>
      <% @preamble.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <!-- <div class="field">
    <%= f.label :meta %><br>
    <%= f.text_field :meta %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preambles/edit.html.erb
<h1>Editing Preamble</h1>

<%= render 'form' %>

<%= link_to 'Show', @preamble %> |
<%= link_to 'Back', preambles_path %>

app/views/preambles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Preambles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Meta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @preambles.each do |preamble| %>
      <tr>
        <td><%= preamble.title %></td>
        <td><%= preamble.body %></td>
        <td><%= preamble.meta %></td>
        <td><%= link_to 'Show', preamble %></td>
        <td><%= link_to 'Edit', edit_preamble_path(preamble) %></td>
        <td><%= link_to 'Destroy', preamble, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Preamble', new_preamble_path %>

app/views/preambles/new.html.erb
<h1>New Preamble</h1>

<%= render 'form' %>

<%= link_to 'Back', preambles_path %>

app/views/preambles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @preamble.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @preamble.body %>
</p>

<p>
  <strong>Meta:</strong>
  <%= @preamble.meta %>
</p>

<%= link_to 'Edit', edit_preamble_path(@preamble) %> |
<%= link_to 'Back', preambles_path %>