config/routes.rb
Rails.application.routes.draw do
  root 'splash#index'
  namespace :api do
    namespace :v1 do
      get 'resources', to: 'resources#index'
    end
  end

  resources :manifests
  resources :considerations
  resources :definitions
  resources :preambles
  resources :recitals
  resources :clauses
end

app/models/recital.rb
class Recital
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Versioning
  include Mongoid::Paranoia

  field :title, type: String
  field :body, type: String
  field :meta, type: Hash
end

app/controllers/recitals_controller.rb
class RecitalsController < ApplicationController
  before_action :set_recital, only: [:show, :edit, :update, :destroy]

  # GET /recitals
  def index
    @recitals = Recital.all
  end

  # GET /recitals/1
  def show
  end

  # GET /recitals/new
  def new
    @recital = Recital.new
  end

  # GET /recitals/1/edit
  def edit
  end

  # POST /recitals
  def create
    @recital = Recital.new(recital_params)

    if @recital.save
      respond_to do |format|
        format.html { redirect_to @recital, notice: 'Recital was successfully created.' }
        format.json { render json: { data: @recital.as_json } }
      end
    else
      render :new
    end
  end

  # PATCH/PUT /recitals/1
  def update
    if @recital.update(recital_params)
      respond_to do |format|
        format.html { redirect_to @recital, notice: 'Recital was successfully updated.' }
        format.json { render json: { data: @recital.as_json } }
      end
    else
      render :edit
    end
  end

  # DELETE /recitals/1
  def destroy
    @recital.destroy
    redirect_to recitals_url, notice: 'Recital was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recital
      @recital = Recital.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def recital_params
      params.require(:recital).permit(:title, :body, :meta)
    end
end

app/helpers/recitals_helper.rb
module RecitalsHelper
end

app/views/recitals/_form.html.erb
<%= form_for(@recital) do |f| %>
  <% if @recital.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recital.errors.count, "error") %> prohibited this recital from being saved:</h2>

      <ul>
      <% @recital.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <!-- <div class="field">
    <%= f.label :meta %><br>
    <%= f.text_field :meta %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recitals/edit.html.erb
<h1>Editing Recital</h1>

<%= render 'form' %>

<%= link_to 'Show', @recital %> |
<%= link_to 'Back', recitals_path %>

app/views/recitals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recitals</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Meta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recitals.each do |recital| %>
      <tr>
        <td><%= recital.title %></td>
        <td><%= recital.body %></td>
        <td><%= recital.meta %></td>
        <td><%= link_to 'Show', recital %></td>
        <td><%= link_to 'Edit', edit_recital_path(recital) %></td>
        <td><%= link_to 'Destroy', recital, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recital', new_recital_path %>

app/views/recitals/new.html.erb
<h1>New Recital</h1>

<%= render 'form' %>

<%= link_to 'Back', recitals_path %>

app/views/recitals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @recital.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @recital.body %>
</p>

<p>
  <strong>Meta:</strong>
  <%= @recital.meta %>
</p>

<%= link_to 'Edit', edit_recital_path(@recital) %> |
<%= link_to 'Back', recitals_path %>