config/routes.rb
Rails.application.routes.draw do
  root 'splash#index'
  namespace :api do
    namespace :v1 do
      get 'resources', to: 'resources#index'
    end
  end

  resources :manifests
  resources :considerations
  resources :definitions
  resources :preambles
  resources :recitals
  resources :clauses
end

app/models/consideration.rb
class Consideration
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Versioning
  include Mongoid::Paranoia

  field :title, type: String
  field :body, type: String
  field :meta, type: Hash
end

app/controllers/considerations_controller.rb
class ConsiderationsController < ApplicationController
  before_action :set_consideration, only: [:show, :edit, :update, :destroy]

  # GET /considerations
  def index
    @considerations = Consideration.all
  end

  # GET /considerations/1
  def show
  end

  # GET /considerations/new
  def new
    @consideration = Consideration.new
  end

  # GET /considerations/1/edit
  def edit
  end

  # POST /considerations
  def create
    @consideration = Consideration.new(consideration_params)

    if @consideration.save
      respond_to do |format|
        format.html { redirect_to @consideration, notice: 'Consideration was successfully created.' }
        format.json { render json: { data: @consideration.as_json } }
      end
    else
      render :new
    end
  end

  # PATCH/PUT /considerations/1
  def update
    if @consideration.update(consideration_params)
      respond_to do |format|
        format.html { redirect_to @consideration, notice: 'Consideration was successfully updated.' }
        format.json { render json: { data: @consideration.as_json } }
      end
    else
      render :edit
    end
  end

  # DELETE /considerations/1
  def destroy
    @consideration.destroy
    redirect_to considerations_url, notice: 'Consideration was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consideration
      @consideration = Consideration.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def consideration_params
      params.require(:consideration).permit(:title, :body, :meta)
    end
end

app/helpers/considerations_helper.rb
module ConsiderationsHelper
end

app/views/considerations/_form.html.erb
<%= form_for(@consideration) do |f| %>
  <% if @consideration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consideration.errors.count, "error") %> prohibited this consideration from being saved:</h2>

      <ul>
      <% @consideration.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <!-- <div class="field">
    <%= f.label :meta %><br>
    <%= f.text_field :meta %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/considerations/edit.html.erb
<h1>Editing Consideration</h1>

<%= render 'form' %>

<%= link_to 'Show', @consideration %> |
<%= link_to 'Back', considerations_path %>

app/views/considerations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Considerations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Meta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @considerations.each do |consideration| %>
      <tr>
        <td><%= consideration.title %></td>
        <td><%= consideration.body %></td>
        <td><%= consideration.meta %></td>
        <td><%= link_to 'Show', consideration %></td>
        <td><%= link_to 'Edit', edit_consideration_path(consideration) %></td>
        <td><%= link_to 'Destroy', consideration, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consideration', new_consideration_path %>

app/views/considerations/new.html.erb
<h1>New Consideration</h1>

<%= render 'form' %>

<%= link_to 'Back', considerations_path %>

app/views/considerations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @consideration.title %>
</p>
<p>
  <strong>Body:</strong>
  <%= @consideration.body %>
</p>

<p>
  <strong>Meta:</strong>
  <%= @consideration.meta %>
</p>

<%= link_to 'Edit', edit_consideration_path(@consideration) %> |
<%= link_to 'Back', considerations_path %>