config/routes.rb
Rails.application.routes.draw do
  root 'splash#index'
  namespace :api do
    namespace :v1 do
      get 'resources', to: 'resources#index'
    end
  end

  resources :manifests
  resources :considerations
  resources :definitions
  resources :preambles
  resources :recitals
  resources :clauses
end

app/models/manifest.rb
class Manifest
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Versioning
  include Mongoid::Paranoia

  field :title, type: String
  field :party, type: String
  field :counterparty, type: String
  field :document, type: Array

  has_and_belongs_to_many :recitals, inverse_of: nil
  has_and_belongs_to_many :considerations, inverse_of: nil
  has_and_belongs_to_many :preambles, inverse_of: nil
  has_and_belongs_to_many :clauses, inverse_of: nil
end

app/controllers/manifests_controller.rb
class ManifestsController < ApplicationController
  before_action :set_manifest, only: [:show, :edit, :update, :destroy]

  # GET /manifests
  def index
    @manifests = Manifest.all
  end

  # GET /manifests/1
  def show
    respond_to do |format|
      format.html
      format.json { render json: res_hash(@manifest) }
    end
  end

  # GET /manifests/new
  def new
    @manifest = Manifest.new
  end

  # GET /manifests/1/edit
  def edit
  end

  # POST /manifests
  def create
    @manifest = Manifest.new(manifest_params)

    if @manifest.save
      respond_to do |format|
        format.html { redirect_to @manifest, notice: 'Manifest was successfully created.' }
        format.json { render json: res_hash(@manifest), notice: 'Manifest was successfully created.' }
      end
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: res_hash(@manifest), status: :bad_request}
      end
    end
  end

  # PATCH/PUT /manifests/1
  def update
    if @manifest.update(manifest_params)
      respond_to do |format|
        format.html { redirect_to @manifest, notice: 'Manifest was successfully updated.' }
        format.json { render json: res_hash(@manifest) }
      end
    else
      respond_to do |format|
        format.html { render :edit }
        format.json { render json: res_hash(@manifest), status: :bad_request}
      end
    end
  end

  # DELETE /manifests/1
  def destroy
    @manifest.destroy
    redirect_to manifests_url, notice: 'Manifest was successfully destroyed.'
  end

  private
    def res_hash(manifest)
      {
        manifest: manifest.as_json,
        preamble: manifest.preambles.group_by(&:id).as_json,
        recital: manifest.recitals.group_by(&:id).as_json,
        consideration: manifest.considerations.group_by(&:id).as_json,
        clause: manifest.clauses.group_by(&:id).as_json,
        definitions: Hash[Definition.all.map { |i| [i.term, i.body] }], # for simplicity right now
      }
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_manifest
      @manifest = Manifest.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def manifest_params
      params.require(:manifest)
            .permit(:title, :party, :counterparty)
            .merge(document: params[:document]) # Hack to allow any nested data TODO fix this.
            .merge(preamble_ids: params[:preamble_ids])
            .merge(recital_ids: params[:recital_ids])
            .merge(consideration_ids: params[:consideration_ids])
            .merge(clause_ids: params[:clause_ids])
    end
end

app/helpers/manifests_helper.rb
module ManifestsHelper
end

app/views/manifests/_form.html.erb
<!-- <%= form_for(@manifest) do |f| %>
  <% if @manifest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@manifest.errors.count, "error") %> prohibited this manifest from being saved:</h2>

      <ul>
      <% @manifest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :party %>
    <%= f.text_field :party %>
  </div>
  <div class="field">
    <%= f.label :counterparty %>
    <%= f.text_field :counterparty %>
  </div>
  <div class="field">
    <%= f.label :document %>
    <%= f.text_area :document %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %> -->
<script type="text/ng-template" id="nodes_renderer1.html">
  <div ui-tree-handle data-nodrag class="tree-node tree-node-content" ng-If="node.data">
    <a class="btn btn-success btn-xs" data-nodrag ng-click="toggle(this)"><span class="glyphicon" ng-class="{'glyphicon-chevron-right': collapsed, 'glyphicon-chevron-down': !collapsed}"></span></a>
    {{node.title}}
  </div>
  <div ng-If="!node.data">
    <div ui-tree-handle class="tree-node tree-node-content">
      <a class="pull-right btn btn-danger btn-xs" data-nodrag ng-click="remove(this)"><span class="glyphicon glyphicon-remove"></span></a>
      <label>Title: </label>{{node.title}}</br>
      <label>Body: </label>{{node.body}}
    </div>
  </div>
  <ol ui-tree-nodes="" ng-model="node.data" ng-class="{hidden: collapsed}">
    <li ng-repeat="node in node.data" ui-tree-node ng-include="'nodes_renderer1.html'">
    </li>
  </ol>
</script>

<script type="text/ng-template" id="all_data_types.html">
  <div ui-tree-handle class="tree-node tree-node-content" data-nodrag>
    <a class="btn btn-success btn-xs" data-nodrag ng-click="toggle(this)"><span class="glyphicon" ng-class="{'glyphicon-chevron-right': collapsed, 'glyphicon-chevron-down': !collapsed}"></span></a>
    {{node.title}}
    <a class="pull-right btn btn-danger btn-xs" data-nodrag ng-click="remove(this)"><span class="glyphicon glyphicon-remove"></span></a>
    <a class="pull-right btn btn-primary btn-xs" data-nodrag ng-click="newSubItem(this)" style="margin-right: 8px;"><span class="glyphicon glyphicon-plus"></span></a>
  </div>
  <ol ui-tree-nodes="" ng-model="node.data">
    <li ng-repeat="node in node.data" ui-tree-node ng-include="'all_data.html'"></li>
  </ol>
</script>
<script type="text/ng-template" id="all_data.html">
  <div ui-tree-handle class="tree-node tree-node-content">
    <label>Title: </label>{{node.title}}</br>
    <label>Body: </label>{{node.body}}
  </div>
</script>

<script type="text/ng-template" id="nodes_renderer.html">
  <div class="tree-node">
    <div class="pull-left tree-handle" ui-tree-handle>
      <span class="glyphicon glyphicon-list"></span>
    </div>
    <div class="tree-node-content">
      <a class="btn btn-success btn-xs" data-nodrag ng-click="toggle(this)">
        <span class="glyphicon" ng-class="{'glyphicon-chevron-right': collapsed, 'glyphicon-chevron-down': !collapsed}"></span>
      </a>
      <a class="pull-right btn btn-danger btn-xs" data-nodrag ng-click="removeMe(this)"><span class="glyphicon glyphicon-remove"></span></a>
      <a class="pull-right btn btn-primary btn-xs" data-nodrag ng-click="newSubItem(this)" style="margin-right: 8px;"><span class="glyphicon glyphicon-plus"></span></a>

      <label for="singleSelect">Type:</label>
      <select name="singleSelect" ng-model="node.type" ng-disabled="node.id != ''">
        <option value="clause">Clause</option>
        <option value="recital">Recital</option>
        <option value="preamble">Preamble</option>
        <option value="consideration">Consideration</option>
        <option value="">---Containters || Groups---</option>
        <option value="signature">Signature Block</option>
        <option value="terms">Terms</option>
        <option value="section">Section</option>
        <option value="recitals">Recitals</option>
      </select></br>

      <label for="title">Contract Title:</label>
      <input name="title" type="text" ng-model="node.title"></input></br>

      <div ng-If="node.type == 'signature'">
        <label for="fields">Fields: </label>
        <input name="fields" ng-model="node.fields" ng-list></br>
      </div>

      <div ng-If="node.type != 'signature'">
        <label for="body">Data Body: </label>
        <textarea name="body" type="text" ng-model="data[node.type][node.id][0].body"></textarea></br>
        <label for="data_title">Data Title:</label>
        <input name="data_title" type="text" ng-model="data[node.type][node.id][0].title"></input></br>
        <a class="btn btn-primary btn-xs" data-nodrag ng-click="updateOrSaveData(node)"><span class="glyphicon glyphicon-pencil"> Save Data</span></a>
      </div>
    </div>
  </div>
  <ol ui-tree-nodes="" ng-model="node.sub_group" ng-class="{hidden: collapsed}">
    <li ng-repeat="node in node.sub_group" ui-tree-node ng-include="'nodes_renderer.html'">
    </li>
  </ol>
</script>

<div class="editManifest" ng-controller="EditManifestCtrl" >
  <div class="row">
    <div class="col-sm-12">
      <button ng-click="saveManifest()">Save</button>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <p>title: <input type="text" ng-model="manifest.title"></input></p>
      <p>party: <input type="text" ng-model="manifest.party"></input></p>
      <p>counterparty: <input type="text" ng-model="manifest.counterparty"></input></p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <button ng-click="expandAll()">Expand all</button>
      <button ng-click="collapseAll()">Collapse all</button>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <div ui-tree="manifestTree" id="tree-root" data-clone-enabled="true">
        <ol ui-tree-nodes="" ng-model="manifest.document">
          <li ng-repeat="node in manifest.document" ui-tree-node ng-include="'nodes_renderer.html'"></li>
        </ol>
      </div>
    </div>
    <div class="col-sm-4">
      <h3>Data Sources</h3>
      <div ui-tree="sourceTree" id="source-root" data-clone-enabled="true" data-nodrop-enabled="true">
        <ol ui-tree-nodes="" ng-model="all_data">
          <li ng-repeat="node in all_data" ui-tree-node ng-include="'nodes_renderer1.html'"></li>
        </ol>
      </div>

      <!-- <div ui-tree id="sources" data-clone-enabled="true" data-nodrop-enabled="true">
        <ol ui-tree-nodes="" ng-model="all_data">
          <li ng-repeat="node in all_data" ui-tree-node ng-include="'all_data_types.html'">
          </li>
        </ol>
      </div> -->
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
      <pre class="code">{{ manifest.document | json }}</pre>
    </div>
    <div class="col-sm-6">
      <pre class="code">{{ data | json }}</pre>
    </div>
  </div>
</div>

app/views/manifests/edit.html.erb
<h1>Editing Manifest</h1>

<%= render 'form' %>

<%= link_to 'Show', @manifest %> |
<%= link_to 'Back', manifests_path %>

app/views/manifests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Manifests</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Party</th>
      <th>Counter party</th>
      <th>Document</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manifests.each do |manifest| %>
      <tr>
        <td><%= manifest.title %></td>
        <td><%= manifest.party %></td>
        <td><%= manifest.counterparty %></td>
        <td><%= manifest.document %></td>
        <td><%= link_to 'Show', manifest %></td>
        <td><%= link_to 'Edit', edit_manifest_path(manifest) %></td>
        <td><%= link_to 'Destroy', manifest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manifest', new_manifest_path %>

app/views/manifests/new.html.erb
<h1>New Manifest</h1>

<%= render 'form' %>

<%= link_to 'Back', manifests_path %>

app/views/manifests/show.html.erb
<p id="notice"><%= notice %></p>
<div class="manifest" ng-controller="ManifestCtrl">
  <h1>
    {{manifest.title}}
  </h1>
  <content-item ng-repeat="item in manifest.document" content="item" data="data"></content-item>

  <%= link_to 'Edit', edit_manifest_path(@manifest) %> |
  <%= link_to 'Back', manifests_path %>
</div>